sudo: required
services:
  - docker
before_install:
  - docker build -t sangeeth472/react_test -f ./client/Dockerfile.dev ./client


scripts:
  - docker run -e CI=true sangeeth472/react_test npm test

after_success:
  - docker build -t 47209104013/multi-client ./client
  - docker build -t 47209104013/multi-nginx ./nginx
  - docker build -t 47209104013/multi-server ./server
  - docker build -t 47209104013/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 47209104013/multi-client
  - docker push 47209104013/multi-nginx
  - docker push 47209104013/multi-server
  - docker push 47209104013/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-844621831305'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

