sudo: required
services:
  - docker
before_install:
  - docker build -t sangeeth472/react_test -f ./client/Dockerfile.dev

scripts:
  - docker run sangeeth472/react_test npm test -- --coverage

after_success:
  - docker build -t sangeeth472/client ./client
  - docker build -t sangeeth472/nginx ./nginx
  - docker build -t sangeeth472/server ./server
  - docker build -t sangeeth472/worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -password-stdin