version: "3"
services:
  client:
    image: "47209104013/multi-client"
    mem_limit: 128m
    host_name: client
  server:
    image: "47209104013/multi-server"
    mem_limit: 128m
    host_name: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
    worker:
      image: "47209104013/multi-worker"
      mem_limit: 128m
      host_name: worker
      environment:
        - REDIS_HOST=$REDIS_HOST
        - REDIS_PORT=$REDIS_PORT
    nginx:
      image: "47209104013/multi-nginx"
      mem_limit: 128m
      host_name: nginx
      ports:
        - "80:80"